import sys
import glob
import os
import subprocess
import re

def cpp_type_to_yuri(cpp_type: str) -> str:
    cpp_type = cpp_type.strip()
    if '*' in cpp_type or 'ptr' in cpp_type:
        return "i64"
    if "double" in cpp_type:
        return "f64"
    if "float" in cpp_type:
        return "f32"
    if "bool" in cpp_type:
        return "i1"
    if any(t in cpp_type for t in ["char", "short", "int32"]):
        return "i32"
    return "i64"

def parse_cpp_signatures(cpp_file):
    signatures = {}
    with open(cpp_file, 'r') as f:
        content = f.read()
    
    pattern = r'([a-zA-Z_][\w\s\*&<>:]+?)\s+([a-zA-Z_]\w*)\s*\(([^)]*)\)\s*(?:const)?\s*\{'
    matches = re.findall(pattern, content)
    
    for ret_type, func_name, params_str in matches:
        ret_type = ret_type.strip()
        ret_type = ret_type.split()[-1] if ' ' in ret_type else ret_type
        
        param_list = []
        if params_str.strip():
            for p in params_str.split(','):
                p_parts = p.strip().split()
                if p_parts:
                    param_type = " ".join(p_parts[:-1]) if len(p_parts) > 1 else p_parts[0]
                    param_list.append(param_type)
                    
        signatures[func_name] = (ret_type, param_list)
    return signatures

def build():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    std_dir = os.path.join(script_dir, "std")
    
    cpp_files = glob.glob(os.path.join(std_dir, "**", "*.cpp"), recursive=True)

    if not cpp_files:
        print("[Build] No C++ standard modules found.")
        return

    std_dir = os.path.join(script_dir, "std")
    os.makedirs(std_dir, exist_ok=True)
    so_file = os.path.join(std_dir, "std.so")

    print(f"[Build] Compiling standard library files recursively into {so_file}...")

    all_sigs = {}
    file_namespace_map = {}

    for cpp_file in cpp_files:
        rel_path = os.path.relpath(cpp_file, std_dir)
        rel_dir, file_name = os.path.split(rel_path)
        file_stem = os.path.splitext(file_name)[0]
        
        parts = []
        if rel_dir:
            parts.extend(rel_dir.split(os.sep))
        parts.append(file_stem)
        expected_ns = "::".join(parts)
        
        file_sigs = parse_cpp_signatures(cpp_file)
        all_sigs.update(file_sigs)
        
        for func_name in file_sigs.keys():
            file_namespace_map[func_name] = expected_ns

    cmd = ["g++", "-shared", "-fPIC", "-O3"] + cpp_files + ["-o", so_file]
    subprocess.run(cmd, check=True)

    nm_result = subprocess.run(["nm", "-D", "--defined-only", so_file], capture_output=True, text=True)
    if nm_result.returncode != 0:
        print("[Build] Warning: nm failed to read standard library symbols.")
        return

    registry_code = "// Auto-generated by opts.py - Do not edit manually\n"
    registry_code += "#include <unordered_map>\n#include <string>\n#include <dlfcn.h>\n#include <vector>\n\n"
    registry_code += "inline void register_auto_symbols(void (*register_fn)(const char*, void*, const char*, const std::vector<std::string>&), void* handle) {\n"

    for line in nm_result.stdout.splitlines():
        parts = line.strip().split()
        if len(parts) >= 3 and parts[1] in ('T', 't', 'W', 'w'):
            mangled_name = parts[2]
            if mangled_name.startswith('_init') or mangled_name.startswith('_fini') or '__cxa' in mangled_name:
                continue
            
            demangle_result = subprocess.run(["c++filt", mangled_name], capture_output=True, text=True, check=True)
            demangled_sig = demangle_result.stdout.strip()
            
            paren_idx = demangled_sig.find('(')
            if paren_idx == -1:
                continue
            
            sig_prefix = demangled_sig[:paren_idx].strip()
            full_func_name = sig_prefix.split()[-1]
            unqualified_name = full_func_name.split('::')[-1]
            
            if unqualified_name not in file_namespace_map:
                continue
            
            expected_ns = file_namespace_map[unqualified_name]
            if not full_func_name.startswith(expected_ns + "::"):
                continue
            flat_prefix = expected_ns.replace("::", "_")
            registered_name = f"{flat_prefix}_{unqualified_name}"

            raw_ret, raw_params = all_sigs.get(unqualified_name, ("i64", []))
            ret_type_mapped = cpp_type_to_yuri(raw_ret)
            mapped_params = [f'"{cpp_type_to_yuri(p)}"' for p in raw_params]

            print(f"name: {registered_name} | namespace: {expected_ns} | mangled: {mangled_name}")

            params_list_code = "{" + ", ".join(mapped_params) + "}"
            registry_code += f'    register_fn("{registered_name}", dlsym(handle, "{mangled_name}"), "{ret_type_mapped}", {params_list_code});\n'

    registry_code += "}\n"

    header_path = os.path.join(script_dir, "include/yuri/auto_symbols.hpp")
    with open(header_path, "w") as f:
        f.write(registry_code)

    print(f"[Build] Namespaced standard library successfully built at {so_file}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 opts.py [build|make]")
        sys.exit(1)

    command = sys.argv[1]

    if command == "make":
        print("[INFO] Configuring project with Ninja and ccache...")
        subprocess.run([
            "cmake", "-B", "build", "-G", "Ninja",
            "-DCMAKE_C_COMPILER_LAUNCHER=ccache",
            "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache"
        ], check=True)

    elif command == "build":
        build()
        print("[INFO] Building project with -j4...")
        subprocess.run(["cmake", "--build", "build", "-j4"], check=True)
    else:
        print(f"Unknown argument: '{command}'. Use 'make' or 'build'.")
        sys.exit(1)

if __name__ == "__main__":
    main()